---
#- hosts: all
- host: localhost
  become: false
  #become: true
  gather_facts: false
  vars_files:
    - vars/default.yml
    
  tasks:
    - name: Create inventory
      add_host:
      hostname: "{{ hostname }}"
    - name: Create a tutum/hello-world container
      docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        volumes:
          - /tutum
        exposed_ports:
          - 80
        restart_policy:
          - always