#Multi-stage YAML pipeline demo.
name: $(BuildDefinitionName).$(DayOfYear)$(Rev:.r)

trigger:
  batch: true # when a build is running, the system waits until the build is completed
  branches:
    include:
      - master
      - feature/*
      - release/*

schedules:
  - cron: "45 8 * * 4"
    branches:
      include:
        - master
    displayName: Weekly Thursday 8h45 am UTC build
    always: true

variables:
  - name: vmImageName
    value: "ubuntu-latest"
  - name: terraform_version
    value: "0.12.26"
  - name: artifact_name
    value: Az-LoadBalancer
  - name: backend_and_main_secret_file_id
    value: "backend-main-jdld-1.json"

resources:
  repositories:
    - repository: Yaml_Templates # identifier (A-Z, a-z, 0-9, and underscore)
      type: github
      endpoint: JamesDLD # name of the service connection to use (for non-Azure Repos types)
      name: JamesDLD/terraform
      ref: refs/tags/0.4.0 # ref name to use, defaults to 'refs/heads/master'

stages:
  - stage: Build
    jobs:
      - job: Terraform_Plan
        displayName: Terraform Plan - Publish a package if Infrastructure changes are identified
        continueOnError: false
        pool:
          vmImage: $(vmImageName)
        steps:
          - checkout: self # self represents the repo where the initial Pipelines YAML file was found
            displayName: "Checking out source code"
            clean: true # whether to fetch clean each time
            persistCredentials: true # set to 'true' to leave the OAuth token in the Git config after the initial fetch

          - task: DownloadSecureFile@1
            displayName: Download secure file $(backend_and_main_secret_file_id)
            inputs:
              secureFile: $(backend_and_main_secret_file_id)

          - template: pipeline/terraform.yml@Yaml_Templates
            parameters:
              version: $(terraform_version)
              path: "./examples/complete"
              package_name: "complete"
              terraform_init: true
              terraform_plan: true
              backend_secret_file_id: $(backend_and_main_secret_file_id)
              main_secret_file_id: $(backend_and_main_secret_file_id)

          - publish: "./ArtifactPublishLocation" # Local path to include in the Artifact
            artifact: "$(artifact_name)"

  - stage: Deploy
    dependsOn: Build
    jobs:
      # track deployments on the environment
      - deployment: Terraform_Apply
        displayName: Terraform Apply - Resources creation
        pool:
          vmImage: $(vmImageName)
        environment: "Terraform_Apply"
        strategy:
          # default deployment strategy
          runOnce:
            deploy:
              steps:
                - template: pipeline/terraform.yml@Yaml_Templates
                  parameters:
                    version: $(terraform_version)
                    package_name: "complete"
                    terraform_apply: true
                    artifact_path: $(Pipeline.Workspace)/$(artifact_name)

  - stage: Deliver
    dependsOn: Deploy
    jobs:
      # track deployments on the environment
      - deployment: Terraform_Destroy
        displayName: Terraform Destroy - Script ok, now deleting the resources
        pool:
          vmImage: $(vmImageName)
        environment: "Terraform_Destroy"
        strategy:
          # default deployment strategy
          runOnce:
            deploy:
              steps:
                - task: DownloadSecureFile@1
                  displayName: Download secure file $(backend_and_main_secret_file_id)
                  inputs:
                    secureFile: $(backend_and_main_secret_file_id)

                - template: pipeline/terraform.yml@Yaml_Templates
                  parameters:
                    version: $(terraform_version)
                    package_name: "complete"
                    terraform_destroy: true
                    main_secret_file_id: $(backend_and_main_secret_file_id)
                    artifact_path: $(Pipeline.Workspace)/$(artifact_name)