resource_group_name  = "terraform-poc-rg"
storage_account_name = "automationtfstate"
container_name       = "devautomationstate"
key                  = "tf.automation.dev.tfstate"
access_key           = "x5GfovaRJYqCCu9iViQ/niqfjY5vynqJLRqZszOCvBPQbKYKejhFKUIsnw3FRUVuIj0hO7F3fWqTXIz744xZRw=="